apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocdnew
spec:
  project: default
  source:
    repoURL: https://github.com/Devyansh1218/argocd-nginx-demo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocdnew
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
